Modernizr.load({test:Modernizr.touch,yep:['css/touch.css'],nope:[]});var test=!1;if("document" in self&&!("classList" in document.createElement("_"))){test=!0}
Modernizr.load({test:test,yep:['external/classList/classList.js'],nope:[]});$(document).ready(function(){$('#flickr').jflickrfeed({limit:10,qstrings:{id:'52617155@N08'},itemTemplate:'<li><a href="{{image_b}}" data-rel="colorbox"><img src="{{image_s}}" alt="{{title}}" /><span class="flickr__hover"></span></a></li>'},function(data){$('#flickr a').colorbox({'data-rel':'colorbox'})});$.colorbox.settings.maxWidth='95%';$.colorbox.settings.maxHeight='95%';var resizeTimer;function resizeColorBox()
{if(resizeTimer)clearTimeout(resizeTimer);resizeTimer=setTimeout(function(){if($('#cboxOverlay').is(':visible')){$.colorbox.load(!0)}},300)}
$(window).resize(resizeColorBox);window.addEventListener("orientationchange",resizeColorBox,!1);$('.custom-tooltip').tooltip();$('#navigation').mobileMenu({triggerMenu:'#navigation-toggle',subMenuTrigger:".sub-nav-toggle",animationSpeed:500});var $block=$('<div/>',{'class':'top-scroll'}).append('<a href="#"/>').hide().appendTo('body').click(function(){$('body,html').animate({scrollTop:0},800);return!1});var didScroll=!1;$(window).scroll(function(){didScroll=!0});setInterval(function scrollHandler(){if(didScroll){didScroll=!1;if($(this).scrollTop()>35){showElem()}else{hideElem()}}},30);function hideElem(){$('.main-nav')[0].classList.remove('fixed-pos');$block.fadeOut()}
function showElem(){$('.main-nav')[0].classList.add('fixed-pos');$block.fadeIn()}});function init_Button(){$('.circle-button').on('mouseenter mouseleave',function(e){e.preventDefault();$(this)[0].classList.toggle('hover')})}
function init_ButtonInfo(){$('.circle-info-wrapper').on('mouseenter mouseleave',function(e){e.preventDefault();$(this)[0].classList.toggle('hover')})}
function init_Roundabout(){$('.roundabout').roundabout({tilt:0.4,minScale:0.5,minOpacity:1,duration:400,easing:'easeOutQuad',enableDrag:!0,dropEasing:'easeOutBack',dragFactor:2,responsive:!0})}
function init_RevoSlider(){$('.banner').revolution({delay:8000,startheight:450,startwidth:1160,hideThumbs:0,thumbWidth:170,thumbHeight:106,thumbAmount:3,navigationType:'thumb',navigationArrows:'none',navigationHAlign:'center',navigationVAlign:'bottom',navigationHOffset:0,navigationVOffset:-45,touchenabled:'on',onHoverStop:'on',stopAtSlide:-1,stopAfterLoops:-1,hideCaptionAtLimit:0,hideAllCaptionAtLilmit:687,fullWidth:'off',hideTimerBar:'on',shadow:0})}
function init_RevoSliderFull(){$('.fullscreenbanner').revolution({delay:8000,startheight:629,startwidth:1920,navigationType:'none',navigationArrows:'solo',navigationStyle:'round',soloArrowLeftHalign:'left',soloArrowLeftValign:'center',soloArrowLeftHOffset:30,soloArrowLeftVOffset:0,soloArrowRightHalign:'right',soloArrowRightValign:'center',soloArrowRightHOffset:30,soloArrowRightVOffset:0,touchenabled:'on',onHoverStop:'on',stopAtSlide:-1,stopAfterLoops:-1,hideThumbs:0,hideCaptionAtLimit:0,hideAllCaptionAtLilmit:463,fullWidth:'off',hideTimerBar:'on',shadow:0,fullWidth:'off'})}
function init_ServicesInfo(){var $slides=$('.decorated-slider .swiper-slide');var $desctipt=$('.service__description');$slides.hover(function(e){$slides.removeClass('swiper-slide--active');$(this)[0].classList.add('swiper-slide--active');var current=$(this).attr('data-order');$desctipt.hide(0);$('.'+current).show(0)})}
function init_Timeline(){$('.timeline').timeLineG({maxdis:280,mindis:100,wraperClass:'timeline-wrap',})}
function init_Gallery(){$('.popup-item').magnificPopup({type:'image',tLoading:'Loading image #%curr%...',mainClass:'mfp-img-mobile',gallery:{enabled:!0,navigateByImgClick:!0,preload:[0,1]},image:{tError:'<a href="%url%">The image #%curr%</a> could not be loaded.',titleSrc:function(item){return item.el.attr('title')}}});$('.popup-item--link').magnificPopup({type:'image',tLoading:'Loading image #%curr%...',mainClass:'mfp-img-mobile',gallery:{enabled:!0,navigateByImgClick:!0,preload:[0,1]},image:{tError:'<a href="%url%">The image #%curr%</a> could not be loaded.',titleSrc:function(item){return item.el.attr('title')}}})}
function init_BlogMasonry(){var $container=$('#post-blocks-container');$container.masonry({'columnWidth':'.block-width-1',itemSelector:'.post--preview-block','gutter':30})}
function init_GalleryMasonry(){var $container=$('#gallery-items-container');$container.masonry({'columnWidth':'.item-width-1',itemSelector:'.gallery-item--random','gutter':12})}
function init_Map(){var myLatlng=new google.maps.LatLng(40.764324,-73.973057);var myOptions={zoom:11,center:myLatlng,disableDefaultUI:!0,panControl:!0,zoomControl:!0,zoomControlOptions:{style:google.maps.ZoomControlStyle.DEFAULT},mapTypeControl:!0,mapTypeControlOptions:{style:google.maps.MapTypeControlStyle.HORIZONTAL_BAR},streetViewControl:!0,mapTypeId:google.maps.MapTypeId.ROADMAP}
var map=new google.maps.Map(document.getElementById("contact__map"),myOptions);var marker=new google.maps.Marker({position:myLatlng,map:map,title:"40.764324,-73.973057"});var infowindow=new google.maps.InfoWindow({content:"<b>My Adress:</b><br> 1 Central Park New York 10019"});google.maps.event.addListener(marker,"click",function(){infowindow.open(map,marker)})}
function init_SliderRange(){$('#slider-range__item').slider({range:!0,min:0,max:60,values:[10,30],slide:function(event,ui){$('#amount').val('$'+ui.values[0]+' - $'+ui.values[1])}});$('#amount').val('$'+$('#slider-range__item').slider('values',0)+' - $'+$('#slider-range__item').slider('values',1))}
function init_raty(){$('.rating__stars').raty({score:function(){return $(this).attr('data-score')},path:'images/icons/',starOff:'star-off.svg',starOn:'star-on.svg',starHalf:'star-half.svg'})}
function init_ColorSelect(){$('.color-filter__item').on('click',function(e){e.preventDefault();$(this)[0].classList.toggle('color-filter__item--selected')})}
function init_TeamSlider(){var teamSwiper=new Swiper('.team__slider',{loop:!0,slidesPerView:4,calculateHeight:!0,mode:'horizontal'});$('.swiper-controls .prev-arrow').on('click',function(e){e.preventDefault();teamSwiper.swipePrev()});$('.swiper-controls .next-arrow').on('click',function(e){e.preventDefault();teamSwiper.swipeNext()});var displayWidth=$(window).width();switch(!0){case(displayWidth>1200):teamSwiper.params.slidesPerView=4;teamSwiper.resizeFix();break;case(displayWidth>970&&displayWidth<=1200):teamSwiper.params.slidesPerView=3;teamSwiper.resizeFix();break;case(displayWidth>520&&displayWidth<=9700):teamSwiper.params.slidesPerView=2;teamSwiper.resizeFix();break;case(displayWidth<=520):teamSwiper.params.slidesPerView=1;teamSwiper.resizeFix();break}
$(window).resize(function(){var displayWidth=$(window).width();switch(!0){case(displayWidth>1200):teamSwiper.params.slidesPerView=4;teamSwiper.reInit();break;case(displayWidth>970&&displayWidth<=1200):teamSwiper.params.slidesPerView=3;teamSwiper.reInit();break;case(displayWidth>520&&displayWidth<=9700):teamSwiper.params.slidesPerView=2;teamSwiper.reInit();break;case(displayWidth<=520):teamSwiper.params.slidesPerView=1;teamSwiper.reInit();break}})}
function init_QoutationSlider(){var qoutationSwiper=new Swiper('.qoutation-slider',{loop:!0,slidesPerView:1,calculateHeight:!0,mode:'horizontal'});$('.qoutation-slider-controls .prev-arrow').on('click',function(e){e.preventDefault();qoutationSwiper.swipePrev()});$('.qoutation-slider-controls .next-arrow').on('click',function(e){e.preventDefault();qoutationSwiper.swipeNext()})}
function init_DecoratedSlider(){var decoratedSwiper=new Swiper('.decorated-slider',{loop:!0,slidesPerView:4,calculateHeight:!0,resizeReInit:!0,mode:'horizontal'});$('.decorated-slider-controls .prev-arrow').on('click',function(e){e.preventDefault();decoratedSwiper.swipePrev()});$('.decorated-slider-controls .next-arrow').on('click',function(e){e.preventDefault();decoratedSwiper.swipeNext()});var displayWidth=$(window).width();switch(!0){case(displayWidth>1200):decoratedSwiper.params.slidesPerView=4;decoratedSwiper.resizeFix();break;case(displayWidth>640&&displayWidth<=1200):decoratedSwiper.params.slidesPerView=3;decoratedSwiper.resizeFix();break;case(displayWidth>450&&displayWidth<=640):decoratedSwiper.params.slidesPerView=2;decoratedSwiper.resizeFix();break;case(displayWidth<=450):decoratedSwiper.params.slidesPerView=1;decoratedSwiper.resizeFix();break}
$(window).resize(function(){var displayWidth=$(window).width();switch(!0){case(displayWidth>1200):decoratedSwiper.params.slidesPerView=4;decoratedSwiper.reInit();break;case(displayWidth>640&&displayWidth<=1200):decoratedSwiper.params.slidesPerView=3;decoratedSwiper.reInit();break;case(displayWidth>450&&displayWidth<=640):decoratedSwiper.params.slidesPerView=2;decoratedSwiper.reInit();break;case(displayWidth<=450):decoratedSwiper.params.slidesPerView=1;decoratedSwiper.reInit();break}})}
jQuery(function($){$('a.panel').click(function(){var $target=$($(this).attr('href')),$other=$target.siblings('.active');if(!$target.hasClass('active')){$other.each(function(index,self){var $this=$(this);$this.removeClass('active').animate({left:$this.width()},500)});$target.addClass('active').show().css({left:-($target.width())}).animate({left:0},500)}})});function abtload(){document.getElementById("collapse1").style.display='block';document.getElementById("collapse2").style.display='none';document.getElementById("collapse3").style.display='none'}
$('.tab').click(function(){$(this).addClass('active').siblings().removeClass('active')})
var didScroll;var lastScrollTop=0;var delta=5;var navbarHeight=$('header').outerHeight();$(window).scroll(function(event){didScroll=!0});setInterval(function(){if(didScroll){hasScrolled();didScroll=!1}},250);function hasScrolled(){var st=$(this).scrollTop();if(Math.abs(lastScrollTop-st)<=delta)
return;if(st>lastScrollTop&&st>navbarHeight){$('header').removeClass('nav-down').addClass('nav-up')}else{if(st+$(window).height()<$(document).height()){$('header').removeClass('nav-up').addClass('nav-down')}}
lastScrollTop=st}
function showfun(){document.getElementById("collapse1").style.display='block';document.getElementById("collapse2").style.display='none';document.getElementById("collapse3").style.display='none'}
function showfun1(){document.getElementById("collapse1").style.display='none';document.getElementById("collapse2").style.display='block';document.getElementById("collapse3").style.display='none'}
function showfun2(){document.getElementById("collapse1").style.display='none';document.getElementById("collapse2").style.display='none';document.getElementById("collapse3").style.display='block'}
$('.navbar-lower').affix({offset:{top:50}});$(window).scroll(function(){if($(this).scrollTop()>400){document.getElementById("scrollbtn").style.display='block'}else{document.getElementById("scrollbtn").style.display='none'}});var $item=$('#carousel-main-banner.carousel .item');var $wHeight=$(window).height();$item.eq(0).addClass('active');$item.height($wHeight);$item.addClass('full-screen');$('#carousel-main-banner.carousel img').each(function(){var $src=$(this).attr('src');var $color=$(this).attr('data-color');$(this).parent().css({'background-image':'url('+$src+')','background-color':$color});$(this).remove()});$(window).on('resize',function(){$wHeight=$(window).height();$item.height($wHeight)});$('.carousel').carousel({interval:5000,pause:"false"})